name: rtd38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - openbabel=3.1.1
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - sphinx==3.4.3
    - sphinx_rtd_theme
    - numpy
    - tensorflow-cpu
    - scipy
    - matplotlib
    - pandas
    - scikit-learn
    - pyyaml