name: rtd38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - openbabel=3.1.1
  - mock
  - pillow
  - sphinx==3.4.3
  - sphinx_rtd_theme
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - numpy
    - tensorflow-cpu
    - tensorflow-gpu
    - scipy
    - matplotlib
    - pandas
    - scikit-learn
    - pyyaml
    - rdkit-pypi  # Or via channels rdkit and conda rdkit
    - tensorflow_addons
    - haste_tf